Feature/375/link component
betagouv/delta-v pull request #398
Opened 2023-02-21 15:31 UTC by Touan95

2023-02-22 08:44 UTC, sabalot requested changes

2023-02-22 08:44 UTC, sabalot commented on front/src/components/business/MenuLink/MenuLink.tsx
> +          {!badgeNumber && iconName && <Icon name={iconName} size="lg" />}
```suggestion
          {badgeNumber !== undefined && iconName && <Icon name={iconName} size="lg" />}
```

c'est mieux de faire comme ça prsk si `badgeNumber === 0` alors `!badgeNumber` ça sera true.

2023-02-23 14:24 UTC, sabalot commented on front/src/components/business/MenuLink/MenuLink.tsx
> +          {!badgeNumber && iconName && <Icon name={iconName} size="lg" />}
je me suis trompé c'est `badgeNumber === undefined` qu'il faut mettre et ça va marcher

2023-02-23 15:53 UTC, Touan95 commented on front/src/components/business/MenuLink/MenuLink.tsx
> +          {!badgeNumber && iconName && <Icon name={iconName} size="lg" />}
Du coup j'ignore la possibilité d'avoir à la fois badgeNumber et iconName

2023-02-24 11:36 UTC, sabalot commented on front/src/components/business/MenuLink/MenuLink.tsx
> +          {!badgeNumber && iconName && <Icon name={iconName} size="lg" />}
La condition pour badge number tu mets `badgeNumber !== undefined`


Et pour icon tu mets  `badgeNumber === undefined && iconName`

2023-02-25 08:36 UTC, sabalot approved these changes

2023-02-26 08:34 UTC, merged