Feature/376/declaration badge status component
betagouv/delta-v pull request #399
Opened 2023-02-21 15:54 UTC by Touan95

2023-02-22 08:59 UTC, sabalot requested changes

2023-02-22 08:59 UTC, sabalot commented on front/src/components/business/DeclarationBadgeStatus/DeclarationBadgeStatus.tsx
> +export enum DeclarationStatus {
c'est ma faute ici, mets plutot en majuscule

```
export enum DeclarationStatus {
  DRAFT = 'draft',
  ...

```

2023-02-22 08:59 UTC, sabalot commented on front/src/components/business/DeclarationBadgeStatus/DeclarationBadgeStatus.tsx
> +      ])}
le mieux c'est de le faire comme ça je pense : 

```
 className={cs(
        {
          'border rounded-lg px-4 py-2 w-fit': true,
          'bg-[#FFE9C8]': status === DeclarationStatus.DRAFT,
          'bg-green-200': status === DeclarationStatus.SUBMITTED,
        ...
        }
```

2023-02-22 08:59 UTC, sabalot commented on front/src/components/business/DeclarationBadgeStatus/DeclarationBadgeStatus.tsx
> +        ]}
ici le mieux c'est de faire une variable avant le return qui appelle une fonction. Cette fonction va faire un switch entre les différentes valeurs.

n'oublie pas que tu peuc pas comparer status à 'draft' prsk c'est un enum. Il faut bien utiliser `DeclarationStatus.DRAFT`

2023-02-22 08:59 UTC, sabalot commented on front/src/components/business/DeclarationBadgeStatus/DeclarationBadgeStatus.stories.tsx
> +};
ça fonctionne comme ça ? je connais peut être pas cette manière de faire, mais normalement faut appeller le composant ?

2023-02-22 16:03 UTC, Touan95 commented on front/src/components/business/DeclarationBadgeStatus/DeclarationBadgeStatus.tsx
> +      ])}
Cette syntaxe n'a pas l'air de fonctionner

2023-02-24 11:38 UTC, sabalot approved these changes

2023-02-24 14:45 UTC, merged