Feature/381/actuality card component
betagouv/delta-v pull request #400
Opened 2023-02-22 07:42 UTC by Touan95

2023-02-22 10:44 UTC, sabalot requested changes

2023-02-22 10:44 UTC, sabalot commented on front/src/components/business/ActualityCard/ActualityCard.tsx
> +            ]}
Ok j'ai capté c'est deux composants différents.

le mieux c'est de faire une variable : 
`const daySinceCreationDate = dayJs().diff(creationDate, 'days');`

et après tu fais daySinceCreationDate > 2 ? `Il y a ${daySinceCreationDate } jours` : dayJs(creationDate).format('DD/MM/YYYY')

Ou comme t'as fait, mais pour l'instant te prends pas la tete et mets juste `dayjs(creationDate).format('DD/MM/YYYY')` tout le temps et après on va lui demander des précisions.

2023-02-22 10:44 UTC, sabalot commented on front/src/components/business/ActualityCard/ActualityCard.tsx
> +            Nomenclature
ça il faut que ça soit un param suplémentaire du composant genre tag

2023-02-22 10:44 UTC, sabalot commented on front/src/components/business/ActualityCard/ActualityCard.tsx
> +      <Typography weight="bold" size="text-2xl" color="black" ellipsis>
le elipsis c'est pas dans le titre il me semble

2023-02-22 16:42 UTC, Touan95 commented on front/src/components/business/ActualityCard/ActualityCard.tsx
> +      <Typography weight="bold" size="text-2xl" color="black" ellipsis>
J'ai mis Ellipsis sur les titres car les cards ont l'air d'avoir une taille fixe. Je les rends dynamiques?

2023-02-24 11:40 UTC, sabalot approved these changes

2023-02-24 14:46 UTC, merged