Add list of declarations
betagouv/delta-v pull request #591
Opened 2023-06-22 08:52 UTC by farid1111

Add list of declarations

2023-06-22 14:38 UTC, sabalot requested changes

2023-06-22 14:38 UTC, sabalot commented on front/src/pages/agent/declarations/index.tsx
> +  };
je pense qu'on devrai le faire différement.

L'enfant a un form avec tous les filtres.
Il a un event quand un des champ du filtre est change.
Il appel à cet event une fonction transmise par le parent avec les données du formulaire en paramètres
le parent dans cette fonction fait le nécessaire (l'appel d'api)

2023-06-22 14:38 UTC, sabalot commented on front/src/stores/declaration/useCase.store.ts
> +    set((state: any) => {
justement j'aurai ici fait une fonction loadDeclaration en lui passant le limite et le offset

2023-06-22 14:49 UTC, farid1111 commented on front/src/pages/agent/declarations/index.tsx
> +  };
ouais mais faut changer tous le composant d' anthony

2023-06-23 12:35 UTC, sabalot requested changes

2023-06-23 12:35 UTC, sabalot commented on back/src/utils/joiCustomValidators.ts
> +
en gros c'est ça que je voulais : 
```typescript
export function validateStatus(str: string): string {
  validatListe(str, Object.values(DeclarationStatus));
}
export function validateMeanOfTransports(str: string): string {
  validatListe(str, Object.values(MeansOfTransport));
}

const validatListe = (str: string, arrayAllowed: string[]): string => {
  const spl: string[] = str.split(',');
  const newSpl = spl.filter((s) => s !== '');
  for (const s of newSpl) {
    if (!arrayAllowed.includes(s as DeclarationStatus)) {
      throw new Error(`${s} is not a good status`);
    }
  }
  return str;
}


```

2023-06-23 15:54 UTC, sabalot approved these changes

2023-06-23 15:57 UTC, merged