fix(multiple): change-password-form validation errors + product search history + favorites
betagouv/delta-v pull request #726
Opened 2024-01-04 10:12 UTC by Touan95

2024-01-08 11:33 UTC, farid1111 commented on front/src/components/autonomous/ConfirmPassword/ConfirmPassword.stories.tsx
> +  // const [open, setOpen] = useState(false);
enlever les commentaires

2024-01-08 11:33 UTC, farid1111 commented on front/src/components/autonomous/ConfirmPassword/ConfirmPassword.stories.tsx
> +// eslint-disable-next-line import/no-extraneous-dependencies
elle sert à rien cette ligne

2024-01-08 11:33 UTC, farid1111 commented on front/src/components/autonomous/ConfirmPassword/ConfirmPassword.tsx
ça devrait pas s'appeler ConfirmPasswordForm plutôt ?

2024-01-08 11:33 UTC, farid1111 commented on back/src/entities/searchProductHistory.entity.ts
> +  searchValue?: string;
je trouve ça bizarre d'ajouté un filtre de recherche dans l'entité ajoute un where dans le repository plutôt

2024-01-08 11:33 UTC, farid1111 commented on back/src/migrations/1704289413340-update-favorite-table.ts
Du coup pas besoin de lui

2024-01-08 11:33 UTC, farid1111 commented on front/src/pages/agent/authentification/mot-de-passe-oublie/changer.tsx
> +          <ConfirmPassword
ConfirmPasswordForm

2024-01-08 15:24 UTC, sabalot requested changes

2024-01-08 15:24 UTC, sabalot commented on back/src/api/product/getSearchHistory/serializer.ts
> +};
faire un type indépendant

2024-01-08 15:24 UTC, sabalot commented on back/src/api/product/getSearchHistory/serializer.ts
> +        searchValue: search.searchValue,
SI product est undefined renvoyer un élément vide dans le tableau

2024-01-08 15:24 UTC, sabalot commented on back/tests/api/product/putSearchHistory/integration.test.ts
> +const searchValue = faker.helpers.maybe(() => faker.commerce.product());
mettre tout le temps ici

2024-01-08 15:24 UTC, sabalot commented on back/tests/api/product/putSearchHistory/validator.test.ts
> +      searchValue: faker.helpers.maybe(() => faker.commerce.product()),
pareil ici

2024-01-08 15:24 UTC, sabalot commented on front/src/api/lib/products.ts
> +};
faire une nouvelle interface

2024-01-08 17:34 UTC, sabalot requested changes
Fix l'historique dans nomenclature

2024-01-09 14:50 UTC, sabalot requested changes

2024-01-09 14:50 UTC, sabalot commented on back/src/api/product/getSearchHistory/serializer.ts
> +export const serializer = (history: SearchProductHistoryEntityInterface[]): any => {
```suggestion
export const serializer = (history: SearchProductHistoryEntityInterface[]): SearchProductHistoryItemWithName[] => {
```

2024-01-09 14:50 UTC, sabalot commented on front/src/pages/agent/nomenclature/recherche/index.tsx
> +  }, [id, search]);
faire deux use effect (un pour l'id et un pour le search)

2024-01-09 16:15 UTC, sabalot approved these changes

2024-01-09 16:16 UTC, merged